name: Deploy to AWS CloudFront

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      DIST_BUCKET : ${{ vars.DIST_BUCKET }}
      ORIGIN_PATH : ${{ vars.ORIGIN_PATH }}
      CLOUDFRONT_DISTRIBUTION_ID : ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: | 
          cd src
          npm install


      - name: Build the React app
        run: npm run build

      - name: copy build files to s3 
        run: | 
          aws s3 rm s3://$DIST_BUCKET/$ORIGIN_PATH --recursive
          aws s3 sync ./dist s3://$DIST_BUCKET/$ORIGIN_PATH 
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"